<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Images\thermometer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Images\thermometer.ico" />
    <None Remove="Resources\Images\weather.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Images\thermometer.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Xceed.Words.NET" Version="4.0.25103.5784" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Presentation\styles\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\thermometer.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\weather.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
